#!/usr/bin/env python3
import socket
import sys
import os
import re

# Send and receive commands"
def send(sock, msg):
  msg = msg + "\r\n"
  sock.send(msg.encode("utf-8"))
  receive = sock.recv(1024).decode("utf-8")
  return receive

# Set up the the socket connection 
def login(ftp):
  username = re.search(r'ftp://(.*?):', ftp).group(1)
  password = re.search(r':(.*?)@', ftp).group(1)
  password = re.search('(?<=:).*', password).group(0)
  host = re.search(r'@(.*?)(/|:)', ftp).group(1)
  
  port = ftp.split(":", 3)[-1]
  port = port.split("/")[0]

  if (len(port) > 3):
    port = "21"
  
  cSock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  ip = socket.gethostbyname(host)
  cSock.connect((ip, int(port)))
  print(cSock.recv(2048))

  # Set the server up
  print(send(cSock, "USER " + username))
  print(send(cSock, "PASS " + password))
  print(send(cSock, "TYPE I"))
  print(send(cSock, "MODE S"))
  print(send(cSock, "STRU F"))

  return cSock

# Open a data channel
def openData(cSock, host):
  msg = send(cSock, "PASV")
  print(msg)
  start = msg.find("(")
  end = msg.find(")")
  pTuple = msg[start+1:end].split(',')
  port = int(pTuple[4])*256 + int(pTuple[5])

  ip = socket.gethostbyname(host)
  dSock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  dSock.connect((ip, port))
  return dSock

# Send a command that need to open a data channel
def protocol(cSock, host, fullCommand):
  dSock = openData(cSock, host)
  print(send(cSock, fullCommand))
  print(dSock.recv(2048))
  dSock.close()
  print(cSock.recv(2048))
  
###############################################################################
if len(sys.argv) == 3:
  cmd = sys.argv[1]
  ftp = sys.argv[2]
  host = re.search(r'@(.*?)(/|:)', ftp).group(1)
  path = ftp.split("/", 3)[-1]

  # open client socket
  cSock = login(ftp)

  # command handling
  if cmd == "ls":
    protocol(cSock, host, "LIST " + path)
  elif cmd == "rm":
    print(send(cSock, "DELE " + path))
  elif cmd == "mkdir":
    print(send(cSock, "MKD " + path))
  elif cmd == "rmdir":
    print(send(cSock, "RMD " + path))
  else: 
    print("Error")
  
  # closing sockets
  send(cSock, "QUIT")
  cSock.close()
  
elif len(sys.argv) == 4:
  cmd = sys.argv[1]
  # ftp to local or local to ftp
  if "ftp" in sys.argv[2]:
    ftp = sys.argv[2]
    local = sys.argv[3]
    ftpToLocal = True
  else:
    ftp = sys.argv[3]
    local = sys.argv[2]
    ftpToLocal = False
  host = re.search(r'@(.*?)(/|:)', ftp).group(1)
  path = ftp.split("/", 3)[-1]
  
  # open client socket
  cSock = login(ftp)
  
  # command handling
  if ftpToLocal:
    # copy from ftp to local
    dSock = openData(cSock, host)
    print(send(cSock, "RETR " + path))
    data = dSock.recv(2048)
    print(data)

    # write to local
    file = open(local, "wb")
    file.write(data)
    file.close()
    
    dSock.close()
    print(cSock.recv(2048))

    # if mv then delete the original
    if cmd == "mv":
      print(send(cSock, "DELE " + path))
  else:
    # copy file from local to ftp 
    file = open(local, "rb")
    data = file.read()
    dSock = openData(cSock, host)
    print(send(cSock, "STOR " + path))
    dSock.send(data)
    dSock.close()
    print(cSock.recv(2048))
    
    # if mv then delete the original
    if cmd == "mv":
      os.remove(local)
      
  # Closing sockets
  send(cSock, "QUIT")
  cSock.close()
else:
  print("Bye")
